#!/bin/bash

PROGNAME=$(basename $0)

usage(){
	echo "$PROGNAME - train with 6-layer NN from MNIST data"
	echo "Usage: $PROGNAME [OPTION...]"
	echo
	echo "Options:"
	echo " -h, --help"
	echo "  Show this usage."
	echo " -t, --test"
	echo "   Only test without updating parameters."
	echo " -i, --input filename(bmp)"
	echo "  Infer what number is written in file."
}

if [ $# -eq 0 ]; then
	exec ./main true
	exit 0
fi

case $1 in
	-h | --help)
		usage
		exit 1
		;;
	-t | --test)
		./main 0
		exit 0
		;;
	-i | --input)
		if [[ ! -z $2 ]]; then
			usage
			exit 1
		fi
		./main 1 $2
		;;
	-*)
		echo "$PROGNAME: illegal option"
		exit 1
		;;
esac
