#!/bin/bash

PROGNAME=$(basename $0)

usage(){
	echo "$PROGNAME - train with 6-layer NN from MNIST data"
	echo "Usage: $PROGNAME [OPTION...]"
	echo
	echo "Options:"
	echo " -h, --help"
	echo "  Show this usage."
	echo " -t, --test"
	echo "  test libralies"
	echo " --inference"
	echo "   Only infer test datas without updating parameters."
	echo " -i, --input filename(bmp)"
	echo "  Infer what number is written in file."
}

if [ $# -eq 0 ]; then
	./main
	exit 0
fi

case $1 in
	-h | --help)
		usage
		exit 1
		;;
	-t | --test)
		./test_main 0
		exit 0
		;;
	--inference)
		./main 1
		;;
	-i | --input)
		if [[ ! -z $2 ]]; then
			usage
			exit 1
		fi
		./main 2 $2
		;;
	-*)
		echo "$PROGNAME: illegal option"
		exit 1
		;;
esac
